import { NeatConfig } from "@firecms/neat";

export const NEAT_PRESET = {
    colors: [
        {
            color: '#FF5772',
            enabled: true,
        },
        {
            color: '#4CB4BB',
            enabled: true,
        },
        {
            color: '#FFC600',
            enabled: true,
        },
        {
            color: '#8B6AE6',
            enabled: true,
        },
        {
            color: '#2E0EC7',
            enabled: true,
        },
        {
            color: '#FF9A9E',
            enabled: true,
        },
    ],
    speed: 2.5,
    horizontalPressure: 3,
    verticalPressure: 4,
    waveFrequencyX: 2,
    waveFrequencyY: 3,
    waveAmplitude: 5,
    shadows: 1,
    highlights: 5,
    colorBrightness: 1,
    colorSaturation: 7,
    wireframe: false,
    colorBlending: 8,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0.0,
    grainIntensity: 0,
    grainSpeed: 1,
    resolution: 1,
    yOffsetWaveMultiplier: 4,
    yOffsetColorMultiplier: 4,
    yOffsetFlowMultiplier: 4,
    enableProceduralTexture: false,
    textureEase: 0.5,
    flowEnabled: true,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,} satisfies NeatConfig;

export const STRIPE_PRESET = {
    colors: [
        {
            color: '#FD113F',
            enabled: true,

        },
        {
            color: '#90E0FF',
            enabled: true,
        },
        {
            color: '#FFC858',
            enabled: true,
        },
        {
            color: '#753BFF',
            enabled: true,
        },
        {
            color: '#f5e1e5',
            enabled: false,
        },
        {
            color: '#B8D4E6',
            enabled: false,
        },
    ],
    speed: 2,
    horizontalPressure: 5,
    verticalPressure: 6,
    waveFrequencyX: 1,
    waveFrequencyY: 2,
    waveAmplitude: 10,
    shadows: 0,
    highlights: 7,
    colorBrightness: 1.05,
    colorSaturation: 0,
    wireframe: false,
    colorBlending: 9,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 0,
    grainIntensity: 0,
    grainSpeed: 0,
    resolution: 1,
    yOffsetWaveMultiplier: 6.5,
    yOffsetColorMultiplier: 5,
    yOffsetFlowMultiplier: 3,
    enableProceduralTexture: false,
    textureEase: 0.4,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,} satisfies NeatConfig;

export const FIRECMS_PRESET = {
    "colors": [
        {
            "color": "#FF5373",
            "enabled": true
        },
        {
            "color": "#FFC858",
            "enabled": true
        },
        {
            "color": "#17E7FF",
            "enabled": true
        },
        {
            "color": "#6D3BFF",
            "enabled": true
        },
        {
            "color": "#f5e1e5",
            "enabled": false
        },
        {
            "color": "#A8E6CF",
            "enabled": false
        }
    ],
    "speed": 2,
    "horizontalPressure": 2,
    "verticalPressure": 5,
    "waveFrequencyX": 2,
    "waveFrequencyY": 2,
    "waveAmplitude": 5,
    "shadows": 10,
    "highlights": 8,
    "colorBrightness": 1,
    "colorSaturation": 10,
    "wireframe": true,
    "colorBlending": 6,
    "backgroundColor": "#003FFF",
    "backgroundAlpha": 1,
    "grainScale": 0,
    grainSparsity: 0,
    "grainIntensity": 0,
    "grainSpeed": 0,
    "resolution": 0.95,
    yOffsetWaveMultiplier: 3.5,
    yOffsetColorMultiplier: 3.5,
    yOffsetFlowMultiplier: 3.5,
    enableProceduralTexture: false,
    textureEase: 0.6,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};
export const FUNKY_PRESET = {
    colors: [
        {
            color: '#FB5066',
            enabled: true,
        },
        {
            color: '#36CCD6',
            enabled: true,
        },
        {
            color: '#FFC600',
            enabled: true,
        },
        {
            color: '#8B6AE6',
            enabled: true,
        },
        {
            color: '#2E0EC7',
            enabled: true,
        },
        {
            color: '#FF9A9E',
            enabled: true,
        },
    ],
    speed: 1,
    horizontalPressure: 3,
    verticalPressure: 3,
    waveFrequencyX: 3,
    waveFrequencyY: 5,
    waveAmplitude: 10,
    shadows: 2,
    highlights: 6,
    colorBrightness: 1.05,
    colorSaturation: 1,
    wireframe: false,
    colorBlending: 3,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 2.4,
    resolution: 0.1,
    yOffset: 10333,
    yOffsetWaveMultiplier: 7.2,
    yOffsetColorMultiplier: 6.8,
    yOffsetFlowMultiplier: 7.7,
    flowDistortionA: 0.4,
    flowDistortionB: 2.6,
    flowScale: 1.9,
    flowEase: 0.94,
    flowEnabled: true,
    enableProceduralTexture: true,
    textureVoidLikelihood: 0.59,
    textureVoidWidthMin: 120,
    textureVoidWidthMax: 330,
    textureBandDensity: 0.1,
    textureColorBlending: 0,
    textureSeed: 478,
    textureEase: 0.86,
    proceduralBackgroundColor: '#003FFF',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const FLUID_PRESET = {
    colors: [
        {
            color: '#899D99',
            enabled: true,
        },
        {
            color: '#5f2727',
            enabled: true,
        },
        {
            color: '#373c38',
            enabled: true,
        },
        {
            color: '#0099bb',
            enabled: true,
        },
        {
            color: '#303B42',
            enabled: true,
        },
        {
            color: '#2E7075',
            enabled: true,
        },
    ],
    speed: 1.5,
    horizontalPressure: 5,
    verticalPressure: 4,
    waveFrequencyX: 4,
    waveFrequencyY: 5,
    waveAmplitude: 0,
    shadows: 4,
    highlights: 4,
    colorBrightness: 1,
    colorSaturation: 0,
    wireframe: true,
    colorBlending: 3,
    backgroundColor: '#202020',
    backgroundAlpha: 0.95,
    grainScale: 2,
    grainSparsity: 0,
    grainIntensity: 0.575,
    grainSpeed: 0.1,
    resolution: 0.7,
    yOffset: 0,
    flowDistortionA: 3.7,
    flowDistortionB: 1.4,
    flowScale: 2.9,
    flowEase: 0.32,
    flowEnabled: true,
    enableProceduralTexture: true,
    textureVoidLikelihood: 0.27,
    textureVoidWidthMin: 60,
    textureVoidWidthMax: 420,
    textureBandDensity: 1.2,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 1,
    proceduralBackgroundColor: '#0E0707',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    yOffsetWaveMultiplier: 5.5,
    yOffsetColorMultiplier: 5.2,
    yOffsetFlowMultiplier: 6.0,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const VIRUS_PRESET = {
    colors: [
        {
            color: '#FB5066',
            enabled: true,
        },
        {
            color: '#00EFFF',
            enabled: true,
        },
        {
            color: '#0F0635',
            enabled: true,
        },
        {
            color: '#8B6AE6',
            enabled: true,
        },
        {
            color: '#0F0635',
            enabled: true,
        },
        {
            color: '#FBFF00',
            enabled: true,
        },
    ],
    speed: 2,
    horizontalPressure: 3,
    verticalPressure: 3,
    waveFrequencyX: 1,
    waveFrequencyY: 0,
    waveAmplitude: 2,
    shadows: 2,
    highlights: 6,
    colorBrightness: 1.05,
    colorSaturation: 3,
    wireframe: false,
    colorBlending: 3,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 5,
    grainSparsity: 0.1,
    grainIntensity: 0.25,
    grainSpeed: 2.4,
    resolution: 0.35,
    yOffset: 17472.722391344607,
    yOffsetWaveMultiplier: 9.5,
    yOffsetColorMultiplier: 13.7,
    yOffsetFlowMultiplier: 9.9,
    flowDistortionA: 1.7,
    flowDistortionB: 2.2,
    flowScale: 2.6,
    flowEase: 0.15,
    flowEnabled: true,
    enableProceduralTexture: true,
    textureVoidLikelihood: 0.44,
    textureVoidWidthMin: 140,
    textureVoidWidthMax: 150,
    textureBandDensity: 1.9,
    textureColorBlending: 0.12,
    textureSeed: 333,
    textureEase: 0.3,
    proceduralBackgroundColor: '#D0DBFB',
    textureShapeTriangles: 46,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,}

export const FLAME_PRESET = {
    "colors": [
        {
            "color": "#FF0069",
            "enabled": true
        },
        {
            "color": "#00EAFF",
            "enabled": true
        },
        {
            "color": "#FFB700",
            "enabled": true
        },
        {
            "color": "#B26AE6",
            "enabled": true
        },
        {
            "color": "#2E0EC7",
            "enabled": true
        }
    ],
    "speed": 4,
    "horizontalPressure": 3,
    "verticalPressure": 4,
    "waveFrequencyX": 10,
    "waveFrequencyY": 0,
    "waveAmplitude": 10,
    "shadows": 5,
    "highlights": 10,
    "colorBrightness": 1,
    "colorSaturation": 2,
    "wireframe": false,
    "colorBlending": 9,
    "backgroundColor": "#003FFF",
    "backgroundAlpha": 1,
    "grainScale": 2,
    grainSparsity: 0,
    "grainIntensity": 0.05,
    "grainSpeed": 1,
    "resolution": 0.5,
    yOffsetWaveMultiplier: 8.5,
    yOffsetColorMultiplier: 7.8,
    yOffsetFlowMultiplier: 9.0,
    enableProceduralTexture: false,
    textureEase: 0.25,
    flowEnabled: true,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const BLOOM_PRESET = {
    colors: [
        {
            color: '#3B00FF',
            enabled: true,
        },
        {
            color: '#FFC858',
            enabled: true,
        },
        {
            color: '#17E7FF',
            enabled: true,
        },
        {
            color: '#215BFF',
            enabled: true,
        },
        {
            color: '#D8A50C',
            enabled: true,
        },
    ],
    speed: 4,
    horizontalPressure: 4,
    verticalPressure: 6,
    waveFrequencyX: 1,
    waveFrequencyY: 1,
    waveAmplitude: 1,
    shadows: 3,
    highlights: 0,
    colorBrightness: 1.15,
    colorSaturation: 0,
    wireframe: false,
    colorBlending: 4,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 0,
    resolution: 1,
    yOffset: 7089,
    yOffsetWaveMultiplier: 3.2,
    yOffsetColorMultiplier: 3.5,
    yOffsetFlowMultiplier: 4,
    flowDistortionA: 3.1,
    flowDistortionB: 2.4,
    flowScale: 1.5,
    flowEase: 0.31,
    flowEnabled: true,
    enableProceduralTexture: false,
    textureVoidLikelihood: 0.06,
    textureVoidWidthMin: 10,
    textureVoidWidthMax: 500,
    textureBandDensity: 0.8,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.65,
    proceduralBackgroundColor: '#FFED00',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: false,
    domainWarpIntensity: 0.6,
    domainWarpScale: 3,
    vignetteIntensity: 0.85,
    vignetteRadius: 0.65,
    fresnelEnabled: true,
    fresnelPower: 3.7,
    fresnelIntensity: 0.7,
    fresnelColor: '#FF0000',
    iridescenceEnabled: true,
    iridescenceIntensity: 0.35,
    iridescenceSpeed: 3.9,
    bloomIntensity: 0.8,
    bloomThreshold: 0.9,
    chromaticAberration: 4,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const SANDS_PRESET = {
    colors: [
        {
            color: '#AD6C1F',
            enabled: true,
        },
        {
            color: '#4CB4BB',
            enabled: true,
        },
        {
            color: '#FFC600',
            enabled: true,
        },
        {
            color: '#835C51',
            enabled: true,
        },
        {
            color: '#836803',
            enabled: true,
        },
    ],
    speed: 1,
    horizontalPressure: 3,
    verticalPressure: 10,
    waveFrequencyX: 2,
    waveFrequencyY: 4,
    waveAmplitude: 8,
    shadows: 1,
    highlights: 5,
    colorBrightness: 1,
    colorSaturation: 7,
    wireframe: false,
    colorBlending: 8,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 3,
    grainSparsity: 0,
    grainIntensity: 0.3,
    grainSpeed: 5,
    resolution: 1,
    yOffsetWaveMultiplier: 2.8,
    yOffsetColorMultiplier: 3.0,
    yOffsetFlowMultiplier: 2.5,
    enableProceduralTexture: false,
    textureEase: 0.55,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const MONTEREY_PRESET = {
    colors: [
        {
            color: '#130437',
            enabled: true,
        },
        {
            color: '#B34BD0',
            enabled: true,
        },
        {
            color: '#210751',
            enabled: true,
        },
        {
            color: '#3511A5',
            enabled: true,
        },
        {
            color: '#8F3E8D',
            enabled: false,
        },
        {
            color: '#FF9A9E',
            enabled: false,
        },
    ],
    speed: 4,
    horizontalPressure: 7,
    verticalPressure: 3,
    waveFrequencyX: 0,
    waveFrequencyY: 0,
    waveAmplitude: 0,
    shadows: 4,
    highlights: 0,
    colorBrightness: 1.95,
    colorSaturation: 2,
    wireframe: false,
    colorBlending: 9,
    backgroundColor: '#210751',
    backgroundAlpha: 1,
    grainScale: 6,
    grainSparsity: 0,
    grainIntensity: 0.125,
    grainSpeed: 0,
    resolution: 1.15,
    yOffset: 75325,
    yOffsetWaveMultiplier: 4.5,
    yOffsetColorMultiplier: 4.8,
    yOffsetFlowMultiplier: 5.2,
    flowDistortionA: 0.4,
    flowDistortionB: 10,
    flowScale: 3.3,
    flowEase: 0.37,
    flowEnabled: true,
    enableProceduralTexture: false,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.06,
    textureVoidWidthMin: 10,
    textureVoidWidthMax: 500,
    textureBandDensity: 0.8,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.38,
    proceduralBackgroundColor: '#003FFF',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: false,
    domainWarpIntensity: 0,
    domainWarpScale: 3,
    vignetteIntensity: 0,
    vignetteRadius: 0.8,
    fresnelEnabled: false,
    fresnelPower: 2,
    fresnelIntensity: 0.5,
    fresnelColor: '#FFFFFF',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 0,
    bloomThreshold: 0.7,
    chromaticAberration: 0,
    shapeType: 'ribbon',
    shapeRotationX: 0,
    shapeRotationY: 0,
    shapeRotationZ: 0,
    shapeAutoRotateSpeedX: 0,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 15,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 1.7,
    planeTwist: 5,
    silhouetteFade: 0.2,
    cylinderFade: 0.08,
    ribbonFade: 0.23,
    cameraLock: false,
    cameraX: 15,
    cameraY: 0.5,
    cameraZ: 0,
    cameraRotationX: 0,
    cameraRotationY: 0,
    cameraRotationZ: 0,
    cameraZoom: 1.45,
};

export const ALEJANDRA_PRESET = {
    colors: [
        {
            color: '#FF5373',
            enabled: true,
        },
        {
            color: '#17E7FF',
            enabled: true,
        },
        {
            color: '#FFC858',
            enabled: true,
        },
        {
            color: '#6D3BFF',
            enabled: true,
        },
        {
            color: '#f5e1e5',
            enabled: false,
        },
    ],
    speed: 6,
    horizontalPressure: 7,
    verticalPressure: 8,
    waveFrequencyX: 1,
    waveFrequencyY: 2,
    waveAmplitude: 8,
    shadows: 4,
    highlights: 6,
    colorBrightness: 0.95,
    colorSaturation: -8,
    wireframe: false,
    colorBlending: 10,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 4,
    grainSparsity: 0,
    grainIntensity: 0.25,
    grainSpeed: 1,
    resolution: 1,
    yOffset: 0,
    flowDistortionA: 1.1,
    flowDistortionB: 0.8,
    flowScale: 1.6,
    flowEase: 0.32,
    flowEnabled: true,
    enableProceduralTexture: false,
    textureVoidLikelihood: 0.27,
    textureVoidWidthMin: 60,
    textureVoidWidthMax: 420,
    textureBandDensity: 1.2,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.22,
    proceduralBackgroundColor: '#0E0707',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    yOffsetWaveMultiplier: 6.2,
    yOffsetColorMultiplier: 5.8,
    yOffsetFlowMultiplier: 6.5,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const LEMON_PRESET = {
    "colors": [
        {
            "color": "#F2FF00",
            "enabled": true
        },
        {
            "color": "#6B00FF",
            "enabled": true
        },
        {
            "color": "#D5ECEB",
            "enabled": true
        },
        {
            "color": "#E4E4E4",
            "enabled": false
        },
        {
            "color": "#F6FFFF",
            "enabled": false
        }
    ],
    "speed": 4,
    "horizontalPressure": 4,
    "verticalPressure": 5,
    "waveFrequencyX": 1,
    "waveFrequencyY": 2,
    "waveAmplitude": 10,
    "shadows": 4,
    "highlights": 7,
    "colorBrightness": 1,
    "colorSaturation": 0,
    "wireframe": false,
    "colorBlending": 7,
    "backgroundColor": "#00A2FF",
    "backgroundAlpha": 1,
    "grainScale": 4,
    grainSparsity: 0,
    "grainIntensity": 0.2,
    "grainSpeed": 2.2,
    "resolution": 0.65,
    yOffsetWaveMultiplier: 5.0,
    yOffsetColorMultiplier: 4.5,
    yOffsetFlowMultiplier: 5.5,
    enableProceduralTexture: false,
    textureEase: 0.48,
    flowEnabled: true,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,}

export const PASTEL_PRESET = {
    colors: [
        {
            color: '#E3D1E6',
            enabled: true,
        },
        {
            color: '#ffc8dd',
            enabled: true,
        },
        {
            color: '#ffafcc',
            enabled: true,
        },
        {
            color: '#C5E2FF',
            enabled: true,
        },
        {
            color: '#00B3FF',
            enabled: false,
        },
    ],
    speed: 4.5,
    horizontalPressure: 6,
    verticalPressure: 6,
    waveFrequencyX: 3,
    waveFrequencyY: 3,
    waveAmplitude: 3,
    shadows: 2,
    highlights: 3,
    colorBrightness: 1,
    colorSaturation: -4,
    wireframe: true,
    colorBlending: 6,
    backgroundColor: '#FF9D9D',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 0,
    resolution: 0.4,
    yOffset: 53047,
    yOffsetWaveMultiplier: 10.9,
    yOffsetColorMultiplier: 3.8,
    yOffsetFlowMultiplier: 6.2,
    flowDistortionA: 2.8,
    flowDistortionB: 2.4,
    flowScale: 1.5,
    flowEase: 0.41,
    flowEnabled: false,
    enableProceduralTexture: false,
    textureVoidLikelihood: 0.06,
    textureVoidWidthMin: 10,
    textureVoidWidthMax: 500,
    textureBandDensity: 0.8,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.72,
    proceduralBackgroundColor: '#FFED00',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: false,
    domainWarpIntensity: 0,
    domainWarpScale: 3,
    vignetteIntensity: 0.3,
    vignetteRadius: 0.6,
    fresnelEnabled: true,
    fresnelPower: 2,
    fresnelIntensity: 0.2,
    fresnelColor: '#FF0000',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.8,
    iridescenceSpeed: 1,
    bloomIntensity: 0.4,
    bloomThreshold: 0.7,
    chromaticAberration: 9,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const CLOUDS_PRESET = {
    colors: [
        {
            color: '#FFFFFF',
            enabled: true,
        },
        {
            color: '#EFE2CE',
            enabled: true,
        },
        {
            color: '#D5ECEB',
            enabled: true,
        },
        {
            color: '#E4E4E4',
            enabled: true,
        },
        {
            color: '#F6FFFF',
            enabled: true,
        },
    ],
    speed: 2,
    horizontalPressure: 4,
    verticalPressure: 5,
    waveFrequencyX: 4,
    waveFrequencyY: 3,
    waveAmplitude: 2,
    shadows: 5,
    highlights: 7,
    colorBrightness: 1,
    colorSaturation: -3,
    wireframe: false,
    colorBlending: 7,
    backgroundColor: '#00A2FF',
    backgroundAlpha: 1,
    grainScale: 100,
    grainSparsity: 0,
    grainIntensity: 0.05,
    grainSpeed: 0.3,
    resolution: 0.35,
    yOffset: 97605,
    yOffsetWaveMultiplier: 5,
    yOffsetColorMultiplier: 4.5,
    yOffsetFlowMultiplier: 5.5,
    flowDistortionA: 0.4,
    flowDistortionB: 3,
    flowScale: 3.3,
    flowEase: 0.53,
    flowEnabled: true,
    enableProceduralTexture: false,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.06,
    textureVoidWidthMin: 10,
    textureVoidWidthMax: 500,
    textureBandDensity: 0.8,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.48,
    proceduralBackgroundColor: '#003FFF',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: true,
    domainWarpIntensity: 0.05,
    domainWarpScale: 0.5,
    vignetteIntensity: 0,
    vignetteRadius: 0.8,
    fresnelEnabled: false,
    fresnelPower: 2,
    fresnelIntensity: 0.5,
    fresnelColor: '#FFFFFF',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 0,
    bloomThreshold: 0.7,
    chromaticAberration: 0,
    shapeType: 'plane',
    shapeRotationX: 0,
    shapeRotationY: 0,
    shapeRotationZ: 0,
    shapeAutoRotateSpeedX: 0,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 15,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 0,
    planeTwist: 0,
    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    cameraLock: true,
    cameraX: 0,
    cameraY: 0,
    cameraZ: 0,
    cameraRotationX: 0,
    cameraRotationY: 0,
    cameraRotationZ: 0,
    cameraZoom: 1,
};

export const DARK_MODE = {
    colors: [
        {
            color: '#000000',
            enabled: true,
        },
        {
            color: '#001129',
            enabled: true,
        },
        {
            color: '#0F0025',
            enabled: true,
        },
        {
            color: '#14080A',
            enabled: true,
        },
        {
            color: '#001129',
            enabled: true,
        },
    ],
    speed: 2,
    horizontalPressure: 4,
    verticalPressure: 4,
    waveFrequencyX: 3,
    waveFrequencyY: 2,
    waveAmplitude: 1,
    shadows: 2,
    highlights: 2,
    colorBrightness: 1,
    colorSaturation: -1,
    wireframe: false,
    colorBlending: 7,
    backgroundColor: '#010101',
    backgroundAlpha: 1,
    grainScale: 2,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 1,
    resolution: 0.75,
    yOffset: 0,
    yOffsetWaveMultiplier: 2.2,
    yOffsetColorMultiplier: 2.5,
    yOffsetFlowMultiplier: 2.8,
    enableProceduralTexture: false,
    textureEase: 0.68,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};

export const NIGHT_DUNES = {
    colors: [
        {
            color: '#554226',
            enabled: true,
        },
        {
            color: '#03162D',
            enabled: true,
        },
        {
            color: '#002027',
            enabled: true,
        },
        {
            color: '#020210',
            enabled: true,
        },
        {
            color: '#02152A',
            enabled: true,
        },
        {
            "color": "#B8D4E6",
            "enabled": false
        }
    ],
    speed: 2,
    horizontalPressure: 3,
    verticalPressure: 5,
    waveFrequencyX: 1,
    waveFrequencyY: 3,
    waveAmplitude: 8,
    shadows: 0,
    highlights: 2,
    colorBrightness: 1,
    colorSaturation: 6,
    wireframe: false,
    colorBlending: 7,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 2,
    grainSparsity: 0,
    grainIntensity: 0.175,
    grainSpeed: 1,
    resolution: 1,
    yOffsetWaveMultiplier: 1.8,
    yOffsetColorMultiplier: 2.0,
    yOffsetFlowMultiplier: 2.2,
    enableProceduralTexture: false,
    textureEase: 0.8,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};


export const PRUSSIAN_BLUE_PRESET = {
    colors: [
        {
            color: '#0b3954',
            enabled: true,
        },
        {
            color: '#087e8b',
            enabled: true,
        },
        {
            color: '#bfd7ea',
            enabled: true,
        },
        {
            color: '#ff5a5f',
            enabled: true,
        },
        {
            color: '#c81d25',
            enabled: true,
        },
        {
            "color": "#A8E6CF",
            "enabled": false
        }
    ],
    speed: 4,
    horizontalPressure: 4,
    verticalPressure: 3,
    waveFrequencyX: 0,
    waveFrequencyY: 0,
    waveAmplitude: 0,
    shadows: 2,
    highlights: 7,
    colorBrightness: 1,
    colorSaturation: 8,
    wireframe: false,
    colorBlending: 5,
    backgroundColor: '#FF0000',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 0,
    resolution: 0.5,
    yOffsetWaveMultiplier: 1.5,
    yOffsetColorMultiplier: 1.8,
    yOffsetFlowMultiplier: 2.0,
    enableProceduralTexture: false,
    textureEase: 0.75,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};
export const NIGHTTIME = {
    colors: [
        {
            color: '#FF3087',
            enabled: true,
        },
        {
            color: '#1B36A6',
            enabled: true,
        },
        {
            color: '#00D3FF',
            enabled: true,
        },
        {
            color: '#6D3BFF',
            enabled: true,
        },
        {
            color: '#492E52',
            enabled: true,
        },
    ],
    speed: 3.5,
    horizontalPressure: 3,
    verticalPressure: 5,
    waveFrequencyX: 8,
    waveFrequencyY: 1,
    waveAmplitude: 5,
    shadows: 3,
    highlights: 2,
    colorBrightness: 1,
    colorSaturation: 7,
    wireframe: false,
    colorBlending: 7,
    backgroundColor: '#003FFF',
    backgroundAlpha: 1,
    grainScale: 2,
    grainSparsity: 0,
    grainIntensity: 0.5,
    grainSpeed: 1,
    resolution: 1.2,
    yOffset: 110380.5,
    yOffsetWaveMultiplier: 3,
    yOffsetColorMultiplier: 3.3,
    yOffsetFlowMultiplier: 3.8,
    flowDistortionA: 5,
    flowDistortionB: 7.7,
    flowScale: 2.6,
    flowEase: 0.36,
    flowEnabled: true,
    enableProceduralTexture: false,
    textureVoidLikelihood: 0.22,
    textureVoidWidthMin: 120,
    textureVoidWidthMax: 150,
    textureBandDensity: 1.9,
    textureColorBlending: 0.12,
    textureSeed: 333,
    textureEase: 0.58,
    proceduralBackgroundColor: '#D0DBFB',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};


export const FOREST_PRESET = {
    "colors": [
        {
            "color": "#005F73",
            "enabled": true
        },
        {
            "color": "#0A9396",
            "enabled": true
        },
        {
            "color": "#94D2BD",
            "enabled": true
        },
        {
            "color": "#E9D8A6",
            "enabled": true
        },
        {
            "color": "#EE9B00",
            "enabled": false
        }
    ],
    "speed": 3,
    "horizontalPressure": 5,
    "verticalPressure": 7,
    "waveFrequencyX": 2,
    "waveFrequencyY": 2,
    "waveAmplitude": 8,
    "shadows": 6,
    "highlights": 8,
    "colorBrightness": 1,
    "colorSaturation": 7,
    "wireframe": false,
    "colorBlending": 10,
    "backgroundColor": "#004E64",
    "backgroundAlpha": 1,
    "grainScale": 3,
    "grainIntensity": 0.3,
    "grainSpeed": 1,
    "resolution": 1,
    enableProceduralTexture: false,
    flowEnabled: false,

    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    shapeType: 'plane',
    cameraLock: true,};



const OCEANS_ELEVEN_PRESET = {
    colors: [
        {
            color: '#0055FF',
            enabled: true,
        },
        {
            color: '#00EAFF',
            enabled: true,
        },
        {
            color: '#FFFFFF',
            enabled: true,
        },
        {
            color: '#6AE6C8',
            enabled: true,
        },
        {
            color: '#0E55C7',
            enabled: true,
        },
    ],
    speed: 4,
    horizontalPressure: 3,
    verticalPressure: 4,
    waveFrequencyX: 4,
    waveFrequencyY: 3,
    waveAmplitude: 2,
    shadows: 7,
    highlights: 5,
    colorBrightness: 1.05,
    colorSaturation: 2,
    wireframe: false,
    colorBlending: 9,
    backgroundColor: '#021337',
    backgroundAlpha: 1,
    grainScale: 2,
    grainSparsity: 0,
    grainIntensity: 0.05,
    grainSpeed: 1,
    resolution: 0.5,
    yOffset: 53839,
    yOffsetWaveMultiplier: 8.8,
    yOffsetColorMultiplier: 7.8,
    yOffsetFlowMultiplier: 9,
    flowDistortionA: 3.7,
    flowDistortionB: 1.4,
    flowScale: 2.9,
    flowEase: 0.32,
    flowEnabled: true,
    enableProceduralTexture: false,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.27,
    textureVoidWidthMin: 60,
    textureVoidWidthMax: 420,
    textureBandDensity: 1.2,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.25,
    proceduralBackgroundColor: '#0E0707',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: true,
    domainWarpIntensity: 0.65,
    domainWarpScale: 6.6,
    vignetteIntensity: 1,
    vignetteRadius: 0.8,
    fresnelEnabled: false,
    fresnelPower: 2,
    fresnelIntensity: 0.5,
    fresnelColor: '#FFFFFF',
    iridescenceEnabled: false,
    iridescenceIntensity: 1,
    iridescenceSpeed: 1,
    bloomIntensity: 2.1,
    bloomThreshold: 0.7,
    chromaticAberration: 0.5,
    shapeType: 'sphere',
    shapeRotationX: 0.21,
    shapeRotationY: 0,
    shapeRotationZ: 0.26,
    shapeAutoRotateSpeedX: 4.2,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 25.5,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 0,
    planeTwist: 0,
    silhouetteFade: 0.29,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    cameraLock: true,
    cameraX: 0,
    cameraY: 0,
    cameraZ: 0,
    cameraRotationX: 0,
    cameraRotationY: 0,
    cameraRotationZ: 0,
    cameraZoom: 1,
};

export const BUBBLE_GUM = {
    colors: [
        {
            color: '#FF5772',
            enabled: true,
        },
        {
            color: '#00B7FF',
            enabled: true,
        },
        {
            color: '#FFC600',
            enabled: true,
        },
        {
            color: '#8B6AE6',
            enabled: true,
        },
        {
            color: '#2E0EC7',
            enabled: true,
        },
        {
            color: '#FF9A9E',
            enabled: true,
        },
    ],
    speed: 2.5,
    horizontalPressure: 2,
    verticalPressure: 4,
    waveFrequencyX: 4,
    waveFrequencyY: 4,
    waveAmplitude: 6,
    shadows: 1,
    highlights: 5,
    colorBrightness: 1,
    colorSaturation: 7,
    wireframe: false,
    colorBlending: 4,
    backgroundColor: '#FFC600',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 1,
    resolution: 0.65,
    yOffset: 102390,
    yOffsetWaveMultiplier: 4,
    yOffsetColorMultiplier: 6.3,
    yOffsetFlowMultiplier: 4,
    flowDistortionA: 0,
    flowDistortionB: 0,
    flowScale: 1,
    flowEase: 0,
    flowEnabled: false,
    enableProceduralTexture: false,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.45,
    textureVoidWidthMin: 200,
    textureVoidWidthMax: 486,
    textureBandDensity: 2.15,
    textureColorBlending: 0.01,
    textureSeed: 333,
    textureEase: 0.5,
    proceduralBackgroundColor: '#000000',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: false,
    domainWarpIntensity: 0,
    domainWarpScale: 3,
    vignetteIntensity: 0,
    vignetteRadius: 0.8,
    fresnelEnabled: true,
    fresnelPower: 2,
    fresnelIntensity: 0.6,
    fresnelColor: '#F90707',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 0,
    bloomThreshold: 0.95,
    chromaticAberration: 1,
    shapeType: 'sphere',
    shapeRotationX: 0,
    shapeRotationY: 0,
    shapeRotationZ: 0,
    shapeAutoRotateSpeedX: 0,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 15,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 0,
    planeTwist: 0,
    silhouetteFade: 0.25,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    cameraLock: false,
    cameraX: 0,
    cameraY: -12,
    cameraZ: 0,
    cameraRotationX: 0,
    cameraRotationY: 0,
    cameraRotationZ: 0,
    cameraZoom: 4.4,
};

export const BLOB_PRESET = {
    colors: [
        {
            color: '#A24141',
            enabled: true,
        },
        {
            color: '#17E7FF',
            enabled: true,
        },
        {
            color: '#FFC600',
            enabled: true,
        },
        {
            color: '#8B6AE6',
            enabled: true,
        },
        {
            color: '#FFFFFF',
            enabled: true,
        },
        {
            color: '#FF75B5',
            enabled: true,
        },
    ],
    speed: 4.5,
    horizontalPressure: 3,
    verticalPressure: 4,
    waveFrequencyX: 2.5,
    waveFrequencyY: 2.5,
    waveAmplitude: 6,
    shadows: 10,
    highlights: 1,
    colorBrightness: 1,
    colorSaturation: 0,
    wireframe: false,
    colorBlending: 3,
    backgroundColor: '#E4E4E4',
    backgroundAlpha: 1,
    grainScale: 4,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 0.5,
    resolution: 0.9,
    yOffset: 63161,
    yOffsetWaveMultiplier: 4,
    yOffsetColorMultiplier: 4,
    yOffsetFlowMultiplier: 10,
    flowDistortionA: 1.2,
    flowDistortionB: 1.8,
    flowScale: 1.5,
    flowEase: 0.25,
    flowEnabled: false,
    enableProceduralTexture: false,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.27,
    textureVoidWidthMin: 60,
    textureVoidWidthMax: 420,
    textureBandDensity: 1.2,
    textureColorBlending: 0.06,
    textureSeed: 333,
    textureEase: 0.5,
    proceduralBackgroundColor: '#0E0707',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: false,
    domainWarpIntensity: 0,
    domainWarpScale: 3,
    vignetteIntensity: 0.25,
    vignetteRadius: 0.35,
    fresnelEnabled: false,
    fresnelPower: 1.3,
    fresnelIntensity: 0,
    fresnelColor: '#ffffff',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.8,
    iridescenceSpeed: 1.5,
    bloomIntensity: 0.1,
    bloomThreshold: 0.1,
    chromaticAberration: 3,
    shapeType: 'sphere',
    shapeRotationX: -2.49,
    shapeRotationY: -0.89,
    shapeRotationZ: 0,
    shapeAutoRotateSpeedX: 1,
    shapeAutoRotateSpeedY: 1.2,
    sphereRadius: 21,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 0,
    planeTwist: 0,
    silhouetteFade: 0.55,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    cameraLock: false,
    cameraX: 22.5,
    cameraY: 0,
    cameraZ: 0,
    cameraRotationX: 0.86,
    cameraRotationY: -0.007,
    cameraRotationZ: 0,
    cameraZoom: 2.6,
} satisfies NeatConfig;


export const COSMIC_VORTEX_PRESET = {
    colors: [
        {
            color: '#0F0635',
            enabled: true,
        },
        {
            color: '#FF00EA',
            enabled: true,
        },
        {
            color: '#00EFFF',
            enabled: true,
        },
        {
            color: '#8B6AE6',
            enabled: true,
        },
        {
            color: '#0F0635',
            enabled: true,
        },
        {
            color: '#FBFF00',
            enabled: false,
        },
    ],
    speed: 3.5,
    horizontalPressure: 4,
    verticalPressure: 5,
    waveFrequencyX: 3,
    waveFrequencyY: 3,
    waveAmplitude: 7,
    shadows: 2,
    highlights: 8,
    colorBrightness: 1.2,
    colorSaturation: 0,
    wireframe: false,
    colorBlending: 5,
    backgroundColor: '#01012B',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 0,
    resolution: 0.8,
    yOffset: 107207,
    yOffsetWaveMultiplier: 9.4,
    yOffsetColorMultiplier: 7.1,
    yOffsetFlowMultiplier: 6.8,
    flowDistortionA: 1.8,
    flowDistortionB: 2.2,
    flowScale: 2,
    flowEase: 0.35,
    flowEnabled: true,
    enableProceduralTexture: false,
    transparentTextureVoid: false,
    textureVoidLikelihood: 0.29,
    textureVoidWidthMin: 120,
    textureVoidWidthMax: 420,
    textureBandDensity: 2.9,
    textureColorBlending: 0.06,
    textureSeed: 536,
    textureEase: 0.93,
    proceduralBackgroundColor: '#775454',
    textureShapeTriangles: 20,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 10,
    domainWarpEnabled: true,
    domainWarpIntensity: 0.8,
    domainWarpScale: 4,
    vignetteIntensity: 0.6,
    vignetteRadius: 0.55,
    fresnelEnabled: true,
    fresnelPower: 2,
    fresnelIntensity: 1.8,
    fresnelColor: '#00EFFF',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 0,
    bloomThreshold: 0.6,
    chromaticAberration: 5,
    shapeType: 'torus',
    shapeRotationX: 0.26,
    shapeRotationY: -0.5,
    shapeRotationZ: 0,
    shapeAutoRotateSpeedX: 0,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 15,
    torusRadius: 23,
    torusTube: 9.8,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 0,
    planeTwist: 0,
    silhouetteFade: 1,
    cylinderFade: 0.08,
    ribbonFade: 0.05,
    cameraLock: false,
    cameraX: 0,
    cameraY: 0,
    cameraZ: 0,
    cameraRotationX: -0.09800000000000006,
    cameraRotationY: -3.752,
    cameraRotationZ: 0,
    cameraZoom: 2.7,
} satisfies NeatConfig;

export const TIME_PRESET = {
    colors: [
        {
            color: '#167CB3',
            enabled: true,
        },
        {
            color: '#CB9854',
            enabled: true,
        },
        {
            color: '#CE96CE',
            enabled: true,
        },
        {
            color: '#E0115F',
            enabled: true,
        },
        {
            color: '#FFFFFF',
            enabled: false,
        },
        {
            color: '#000000',
            enabled: false,
        },
    ],
    speed: 2.5,
    horizontalPressure: 5,
    verticalPressure: 5,
    waveFrequencyX: 2,
    waveFrequencyY: 3,
    waveAmplitude: 6,
    shadows: 2,
    highlights: 0,
    colorBrightness: 0.9,
    colorSaturation: -3,
    wireframe: false,
    colorBlending: 5,
    backgroundColor: '#A1A4B7',
    backgroundAlpha: 1,
    grainScale: 0,
    grainSparsity: 0,
    grainIntensity: 0,
    grainSpeed: 0,
    resolution: 0.4,
    yOffset: 28659,
    yOffsetWaveMultiplier: 1,
    yOffsetColorMultiplier: 4.8,
    yOffsetFlowMultiplier: 5.3,
    flowDistortionA: 3.7,
    flowDistortionB: 0.8,
    flowScale: 1.6,
    flowEase: 0.32,
    flowEnabled: true,
    enableProceduralTexture: false,
    transparentTextureVoid: true,
    textureVoidLikelihood: 0.29,
    textureVoidWidthMin: 120,
    textureVoidWidthMax: 420,
    textureBandDensity: 2.9,
    textureColorBlending: 0.06,
    textureSeed: 536,
    textureEase: 0.93,
    proceduralBackgroundColor: '#775454',
    textureShapeTriangles: 48,
    textureShapeCircles: 15,
    textureShapeBars: 15,
    textureShapeSquiggles: 27,
    domainWarpEnabled: true,
    domainWarpIntensity: 0.1,
    domainWarpScale: 2.4,
    vignetteIntensity: 0.45,
    vignetteRadius: 0.55,
    fresnelEnabled: false,
    fresnelPower: 2.7,
    fresnelIntensity: 1.3,
    fresnelColor: '#F7E7CE',
    iridescenceEnabled: false,
    iridescenceIntensity: 0.5,
    iridescenceSpeed: 1,
    bloomIntensity: 1.9,
    bloomThreshold: 0.6,
    chromaticAberration: 17,
    shapeType: 'ribbon',
    shapeRotationX: 0.3480000000000001,
    shapeRotationY: -26.783,
    shapeRotationZ: -0.29,
    shapeAutoRotateSpeedX: 0,
    shapeAutoRotateSpeedY: 0,
    sphereRadius: 15,
    torusRadius: 15,
    torusTube: 5,
    cylinderRadius: 10,
    cylinderHeight: 40,
    planeBend: 2.3,
    planeTwist: -2.9,
    silhouetteFade: 0.83,
    cylinderFade: 0.08,
    ribbonFade: 0.31,
    cameraLock: false,
    cameraX: 0,
    cameraY: 0,
    cameraZ: 0,
    cameraRotationX: -0.014,
    cameraRotationY: -0.23800000000000002,
    cameraRotationZ: 0,
    cameraZoom: 1,
} satisfies NeatConfig;


export const PRESETS = {
    "Neat": NEAT_PRESET,
    "Time": TIME_PRESET,
    "Fluid": FLUID_PRESET,
    "Flame": FLAME_PRESET,
    "Funky": FUNKY_PRESET,
    "Alejandra": ALEJANDRA_PRESET,
    "Monterey": MONTEREY_PRESET,
    "Virus": VIRUS_PRESET,
    "Blob": BLOB_PRESET,
    "Sands": SANDS_PRESET,
    "Nighttime": NIGHTTIME,
    "Prussian": PRUSSIAN_BLUE_PRESET,
    "Clouds": CLOUDS_PRESET,
    "Lemon": LEMON_PRESET,
    "Dark Mode": DARK_MODE,
    "FireCMS": FIRECMS_PRESET,
    "Stripe": STRIPE_PRESET,
    "Pastel": PASTEL_PRESET,
    "Cosmic Vortex": COSMIC_VORTEX_PRESET,
    "Bloom": BLOOM_PRESET,
    "Night Dunes": NIGHT_DUNES,
    "Forest": FOREST_PRESET,
    "Bubble Gum": BUBBLE_GUM,
    "Oceans Eleven": OCEANS_ELEVEN_PRESET,
};

export const fontMap = {
    Neat: 'font-sans',
    "Blob": 'font-pacifico',
    "Cosmic Vortex": 'font-vt323',
    "Time": 'font-concert-one',
    FireCMS: 'font-rubik',
    Fluid: 'font-source-serif-pro',
    Lemon: 'font-londrina',
    Flame: 'font-fredoka',
    "Dark Mode": 'font-source-serif-pro',
    Virus: 'font-lobster',
    Alejandra: 'font-lobster',
    Bloom: 'font-quicksand',
    Sands: 'font-inconsolata',
    Stripe: 'font-oswald',
    Nighttime: 'font-lobster',
    Prussian: 'font-alegreya',
    Clouds: 'font-nunito-sans',
    Monterey: 'font-merriweather',
    Pastel: 'font-poppins',
    Oceanic: 'font-libre-baskerville',
    "Oceans Eleven": 'font-source-serif-pro',
    "Bubble Gum": 'font-fredoka',
};
