// Regenerates src/version.ts from package.json so the runtime version
// constant can never drift from the published version. Runs as part of
// the build script.
const fs = require("fs");
const path = require("path");

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf8"));
const content = `// Auto-generated by scripts/sync-version.js — do not edit manually.
export const NEAT_VERSION = "${pkg.version}";
`;

const target = path.join(__dirname, "..", "src", "version.ts");
if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content) {
    fs.writeFileSync(target, content);
    console.log(`Synced src/version.ts to v${pkg.version}`);
}
